# -*- ruby -*-

require "rubygems"
require "hoe"

require_relative('lib/qnx/version')
# Hoe.plugin :compiler
# Hoe.plugin :gem_prelude_sucks
# Hoe.plugin :inline
# Hoe.plugin :racc
# Hoe.plugin :rcov
# Hoe.plugin :rubyforge

Hoe.spec "vagrant-guest-qnx" do |prj|
  developer("Vassilis Rizopoulos", "vassilisrizopoulos@gmail.com")
  license "MIT"
  prj.version = VagrantQnx::Version::STRING
  prj.summary='A vagrant plugin for QNX Neutrino RTOS guests'
  prj.description=prj.paragraphs_of('README.md',3..6).join("\n\n")
  prj.changes= prj.paragraphs_of('History.txt',0..1).join("\n\n")
  prj.urls=["http://github.com/damphyr/vagrant-qnx/vagrant-guest-qnx"]
  prj.extra_deps=[]
  prj.extra_dev_deps=[]
end
# vim: syntax=ruby
